In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('play_tennis.csv')

In [3]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

 Problem 1 

 outlook = Sunny, Temp = Hot , Humidity = HIgh, wind = weak 

 Play or No play?

Solution 

From the Naive Bayes

P(Yes | Sunny, Hot , High, Weak ) = P ( Sunny | Yes) * P( Hot | Yes ) * P(High | Yes )  * P( Weak | Yes ) * P(Yes)


P(NO | Sunny, Hot , High, Weak ) = P ( Sunny | NO) * P( Hot | NO ) * P(High | NO )  * P( Weak | NO ) * P (No)

#### Compare and decide using the Maximum a Posteriori rule

 Problem 2 

 outlook = Overcast, Temp = Cold , Humidity = Low , wind = weak 

 Play or No play?

Solution 

From the Naive Bayes

P(Yes | Overcast , Cold , Low, Weak ) = P ( Overcast  | Yes) * P( Cold | Yes ) * P(Low | Yes )  * P( Weak | Yes ) * P(Yes)


P(NO | Overcast , Cold , Low, Weak ) = P ( Overcast  | NO) * P( Cold | NO ) * P(Low | NO )  * P( Weak | NO ) * P (No)

#### Compare and decide using the Maximum a Posteriori rule

### Naive uses the Look Up table. It uses some data structure like dict to store all the possible probability and use it later on the prediction .

### It Creates the lookUp table during the training phase

Manually creating the lookup table

In [ ]:


df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
# P(yes)
# P(no)
py = 9/14
pn= 5/14
print(py,pn)

0.6428571428571429 0.35714285714285715

In [6]:
# outlook probs

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [7]:
Pon = 0  # Prob  overcast and no 
Prn = 2/5 # prob rain and no 
Psn = 3/5


Poy = 4/9
Pry = 3/9
Psy = 2/9

In [8]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [9]:
# Temp probs

PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [11]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [12]:
# humidity probs

PHighNO = 4/5
PNormalNo= 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [13]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [14]:
# wind probs 

PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [15]:
# outlook = sunny, Temp = Hot, Humidity = High, Wind = Weak 

Pyes = py*Psy*PHotYes*PHighYes*PWeakYes
print(Pyes)

0.007054673721340388

In [16]:
Pno = pn*Psn*PHotNo*PHighNO*PWeakNo
print(Pno)

0.02742857142857143

# So No Play