In [2]:
import pandas as pd 
import requests

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [9]:
temp_df= pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,126.5761,8.956,1826
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,110.5352,8.723,30649
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,321.7840,8.710,3159
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,129.8917,8.692,5486
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,40.9483,8.687,23089
5,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,28.6729,8.571,14003
6,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,27.3547,8.570,17556
7,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,27.9563,8.572,678
8,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,24.0207,8.563,10074
9,1383731,Protector,Nikki's life is shattered when her daughter is...,2026-02-20,24.5341,8.529,376
10,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,38.6223,8.500,18461
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,45.4795,8.531,35984
12,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,14.8540,8.510,4599
13,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,28.7295,8.506,19374
14,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,42.0564,8.500,26721
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,10.5495,8.500,355
16,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,35.8259,8.493,20793
17,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,39.3278,8.482,30346
18,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,30.5330,8.481,12651
19,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,66.8713,8.479,40139

TMDB API : https://developers.themoviedb.org/ RapidAPI : https://rapidapi.com/collection/list-of-free-apis JSON Viewer: http://jsonviewer.stack.hu/

In [17]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [19]:
# for i in range(1,429):
#     response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
#     temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
#     df = df.append(temp_df,ignore_index=True)

In [ ]:


movies = []

for i in range(1, 429):
    response = requests.get(
        f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}'
    )

    movies.extend(response.json()['results'])

df = pd.DataFrame(movies)[
    ['id', 'title', 'overview', 'release_date',
     'popularity', 'vote_average', 'vote_count']
]

print(df.shape)